name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
      max-parallel: 5

    steps:
    - name: Python ${{ matrix.python-version }} sample
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        architecture: x64
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run code
      run: python3 code/starter.py
